version: '3'
services:
  veggieTables:
    container_name: veggieTables
    image: postgres:15-alpine
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - veggieTables:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=tuber
      - POSTGRES_PASSWORD=tuber
      - POSTGRES_DB=tuber
    #network_mode: host
#  backend:
#    container_name: backend
#    build: ./backend/
#    restart: always
#    ports:
#      - "8080:8080"
#    environment:
#      # Vite takes care of most of this for us, but it's good practice for other backends
#      - VITE_DB_HOST=postgres
#      - VITE_IP_ADDR=0.0.0.0
#      - VITE_PORT=8080
#      - VITE_LOGS_DIR=logs/
#    depends_on: #This is a lie
#      - postgres
volumes:
  veggieTables:
    driver: local
