version: '3'
services:

  backend:
    container_name: backend
    build: ./backend/
    restart: always
    ports:
      - "8080:8080"
    environment:
      - VITE_DB_HOST=postgres
      - VITE_IP_ADDR=0.0.0.0
      - VITE_PORT=8080
      - VITE_LOGS_DIR=logs/
      - VITE_DB_PORT=5433
      - VITE_DB_USER=tuber
      - VITE_DB_PASS=tuber
      - VITE_DB_NAME=ruber
    depends_on:
      - veggieTables # name of SERVICE it depends on

  frontend:
    container_name: frontend
    build: ./frontend/
    restart: always
    ports:
      - "88:80" # map here for convinience sake, to avoid collisions with local server
    environment:
      - VITE_BACKEND_IP=backend
      - VITE_BACKEND_PORT=8080

  veggieTables:
    container_name: veggieTables
    image: postgres:15-alpine
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - veggieTables:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=tuber
      - POSTGRES_PASSWORD=tuber
      - POSTGRES_DB=tuber

  searchPyService:
    container_name: searchPyService
    build: ./searchPyService/
    restart: always
    ports:
      - "8000:8000" #is this right?
    environment:
      - DATABASE_URL=postgres://tuber:tuber@postgres/tuber
    depends_on:
      - veggieTables #name of SERVICE it depends on

volumes:
  veggieTables:
    driver: local

